### ISSUE TITLE
Bug: undefined function acf_get_field_groups() when ACF not installed

### ISSUE THREAD

**Issue by heybran** [BoonBand/Post-Type-Class-Generator#1]
Hey BoonBand team,

I found this plugin while I was searching for WordPress Developer job. If this is allowed, I'm opening an issue to report a tiny bug that I found when using this plugin.

## What happened

When I install this plugin, go to `Tools` -> `Post Type Class Generator` and choose `Post`, then click `Generate Class`, it throws this error.

`Fatal error: Uncaught Error: Call to undefined function acf_get_field_groups() in /Users/brandon/Local Sites/webinars-manager/app/public/wp-content/plugins/Post-Type-Class-Generator/post-type-class-generator-by-boon-band.php:15 `

From this line of code:

```php
$temp = acf_get_field_groups(array('post_type' => $post_type));
```

This error happens because I don't have ACF installed on this site.

## What should happen?

We should check if `acf_get_field_groups` function exists first?

**Comment by heybran** [comment]
If you welcome PR, I've sent a tiny PR adding a defensive coding for this `acf_get_field_groups` function. Thanks

**Comment by VXXXO** [comment]
Thank you @heybran 
Accepted
